### PR TITLE
Add a layer for existing cycle paths. #299

### PR DESCRIPTION
**Pull request by dabreegster**
Demo: https://acteng.github.io/atip/cycle_path_layer/browse.html

See issue for big TODOs and reference maps.

### CODE REVIEW

**Review by dabreegster — COMMENTED** [review]
https://github.com/acteng/atip/assets/1664407/3ef1ec90-28dd-4ed1-bb8f-68da93b47905

**Comment by Robinlovelace** [comment]
Sounds really promising. Taking a look!

**Comment by Robinlovelace** [comment]
Simple sanity check for Leeds passes the test, this has the main ones:

image

There are traffic calming interventions that may be worth adding.

Main bit of feedback on this: important to have Walking infrastructure also, may be harder..

**Comment by Robinlovelace** [comment]
Overall: big :+1:

**Review by Pete-Y-CS — APPROVED** [review]

**Pull request merged**
