### PR TITLE
Prototype scheme- and intervention-level fields for a new pipeline sc…

### PR DESCRIPTION
**Pull request by dabreegster**
…hema. #355 

Demo: https://acteng.github.io/atip/pipeline_forms/scheme.html?authority=LAD_Adur&schema=pipeline

- [x] Use .geojson file extension instead of .txt, at least for this mode, since we're not using SmartSurvey
- [ ] Make the scheme details more prominent -- maybe ask it upfront, or make the button way more obvious
- [ ] Make a component for numeric input (and note https://design-system.service.gov.uk/components/text-input/ recommends against it...)
- [ ] Think through how the "is alternative?" would work
- [ ] Figure out how to ask for the coverage polygon
- [x] Add warnings for the new per-intervention fields
- [x] Mark required vs optional fields, and maybe re-order things

### CODE REVIEW

**Comment by Robinlovelace** [comment]
From a quick glance, looking great to me!

image

**Comment by Robinlovelace** [comment]
Switching between snapping and straight line mode with Shift feels great, smoother than before? Niggle: I think the text with "Shift" is different from the nice text we now use as default:

image

**Comment by dabreegster** [comment]
Robin, this PR and the demo link is for new forms both intervention- and scheme-wide. Please try out snapping/freehand points in routes at https://github.com/acteng/atip/pull/376.

**Comment by Robinlovelace** [comment]
> Robin, this PR and the demo link is for new forms both intervention- and scheme-wide. Please try out snapping/freehand points in routes at #376.

Aha I see what you mean. Will give it a go now!

**Comment by Robinlovelace** [comment]
Overall: looking really great, I love the big form for scheme level details. 

image

**Review by Pete-Y-CS — APPROVED** [review]

**Pull request merged**
