### PR TITLE
Rename the layers to layerToggles

### PR DESCRIPTION
**Pull request by Pete-Y-CS**

### CODE REVIEW

**Comment by dabreegster** [comment]
Hmm... "Hospital Layer Toggle" makes it sound like the component is just a toggle control, but it defines the layer itself. The checkbox and toggling visibility behavior is just part of it -- setting up the maplibre source and layer styles and the help button are just as important.

I'd agree `OptionalLayer` is a poor name at this point. It's more accurately `PolygonAmenityLayer`, a convenience for schools and hospitals and other similar layers to come. MRN and the PC boundary one need different things, so they don't use it.

**Comment by Pete-Y-CS** [comment]
Well the components are the toggles, right? The fact that they have the logic to display the layer is secondary when you're using them in a page? To me it almost suggests that these should be called LayerToggle still, but call out to some ts  which actually draws the layer?

**Comment by Pete-Y-CS** [comment]
I guess the thinking behind this: the name is for a Svelte component so it should describe its function in a page and what it actually renders.

**Comment by dabreegster** [comment]
> the name is for a Svelte component so it should describe its function in a page and what it actually renders.

This makes sense to me. The function on the page includes the small colored box as legend, the toggle, and the help/more info button. So what if we name these "xyz LayerControl.svelte"? And OptionalLayer -> PolygonAmenityLayerControl?

**Comment by Pete-Y-CS** [comment]
Sounds perfect

**Pull request merged**
